steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/myresume-457817/ai-workshop', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/myresume-457817/ai-workshop']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'ai-workshop'
  - '--image'
  - 'gcr.io/myresume-457817/ai-workshop'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '512Mi'
  - '--cpu'
  - '1'
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--port'
  - '8080'
  - '--set-env-vars'
  - 'NODE_ENV=production,VITE_API_URL=https://ai-workshop-711582759542.us-central1.run.app'
  - '--update-secrets'
  - 'SENDGRID_API_KEY=SENDGRID_API_KEY:latest,GMAIL_USER=ADMIN_EMAIL:latest'

images:
- 'gcr.io/myresume-457817/ai-workshop'

options:
  logging: CLOUD_LOGGING_ONLY 