version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - PORT=3001
      - VITE_API_URL=http://localhost:3001
    restart: unless-stopped 